### ISSUE TITLE
Printers not deploying

### ISSUE THREAD

**Issue by grandmasterv** [dlwyatt/PolicyFileEditor#10]
I'm having a problem getting LGPO deployed with the PolicyFileEditor to trigger installation of network printers on Windows 10 Enterprise v1709.  The printers show up properly in `Windows Settings -> Deployed Printers` but something does not trigger the actual installation even when I run `gpupdate /force`.  If I manually change anything with the LGPO there by removing or adding a printer something gets triggered and the printers settings I had previously added with the PolicyFileEditor deploy.  I have also tried restarting the computer to no effect.  

I'm very new to GPO but in troubleshooting this issue I saw something that mentioned that printers are handled by a GPO Extension.  I'm wondering if these extensions are not being triggered to update when I call `gpupdate /force`.  I'm sorry if this is not an issue with the PolicyFileEditor and just a behaviour of the LGPO. 

I would also like to say thank you so much for making this Powershell module!  Its super rad and very useful.  Cheers!

**Comment by dlwyatt** [comment]
The module's really only intended to handle settings that are found under "Administrative Templates".  As you mentioned, other group policy extensions may do different things in addition to (or instead of) setting registry values, and I couldn't really tell you what to expect.  Sorry!

**Comment by grandmasterv** [comment]
Thanks for the clarification!
