### ISSUE TITLE
Exception from HRESULT: 0x80131515

### ISSUE THREAD

**Issue by karezza** [dlwyatt/PolicyFileEditor#6]
When I attempted to import:

PS > Import-Module PolicyFileEditor -Force
Add-Type : Could not load file or assembly 

I've unblocked the DLL.  Turns out I can load the DLL with:

Add-Type -Path C:\users\...\PolFileEditor.dll -ErrorAction Stop

....
Why is the module not able to load the dll?

**Comment by erwinwildenburg** [comment]
It works fine with me, no error.

**Comment by dlwyatt** [comment]
Does that continue to happen after you start a fresh PowerShell session?  There's some caching that happens with regard to blocking / unblocking a file, as I recall.

**Comment by karezza** [comment]
This does appear to be the fix.

For some reason I had to open a new powershell and then I was able to import the module.  Maybe it is as you said, because I had to unblock the DLL.

Thank you.
